version: "3.7"
services:
  coturn_app:
    image: zayuh/coturn_app:lasted
    user: "1003:983"
    ports:
      - "24999:24999"
      - "25000:25100"
      - "25000:25100/udp"
    restart: always
    build: .
    volumes:
      - "~/data/profile:/src/coin/resource/profile"
      - "~/data/image:/src/coin/resource/image"
