version: "3.7"
services:
  meeting_server_app:
    image: zayuh/meeting_server_app:lasted
    ports:
      - "24002:3000"
    restart: always
    build: .
    links:
      - metting-mongodb
    volumes:
      - "~/data-docker/uploads:/data/uploads"

  metting-mongodb:
    image: mongo:5.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: meet
      MONGO_INITDB_ROOT_PASSWORD: Duan2.22ti!
    command: ["--bind_ip", "0.0.0.0"]
    ports:
      - "24003:27017"
    volumes:
      - "~/data-docker/mongodb:/data/db"
    restart: always
